language: node_js
sudo: false
node_js:
    - "7.8"
install:
    - npm install
before_script:
    - shopt -s globstar
script:
    - ./node_modules/istanbul/lib/cli.js --include-all-sources cover ./node_modules/mocha/bin/_mocha -- -R spec ./test/**/*.js
after_script:
    - "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
