language: node_js
sudo: false
node_js:
    - "7.8"
install:
    - npm install
script:
    - npm run-script test-travis
after_script:
    - "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
