sudo: required
services:
  - docker
before_install:
  - curl -L https://github.com/docker/compose/releases/download/1.12.0/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

before_script:
    - shopt -s globstar
script:
    - ./node_modules/istanbul/lib/cli.js --include-all-sources cover ./node_modules/mocha/bin/_mocha -- -R spec ./test/**/*.js
    - docker-compose -f docker-compose-test.yml up --build
after_script:
    - "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
