env:
    DOCKER_COMPOSE_VERSION: 3.0.0
before_install:
  - docker-compose --version
install:
    - npm install
before_script:
    - shopt -s globstar
script:
    - ./node_modules/istanbul/lib/cli.js --include-all-sources cover ./node_modules/mocha/bin/_mocha -- -R spec ./test/**/*.js
after_script:
    - "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
