version: '3.0'
services:
    node:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "5000:5000"
        volumes:
            - ./:/ava
        entrypoint: /app/run.sh
