version: '3.0'
services:
    nodetest:
        build:
            context: .
            dockerfile: Dockerfile.test
        ports:
            - "5000:5000"
        volumes:
            - ./:/ava-test
        command: /app/test.sh
