FROM node:7.9.0
MAINTAINER James Longman <jameslongman2@gmail.com>

### Add dependencies ###
RUN apt update

### Add bash script to Docker image ###
COPY docker/test.sh /app/test.sh

RUN chmod +x /app/test.sh

### Bundle source files into the Docker image's app directory ###
COPY . /app
